# Generated by Django 4.1.4 on 2023-01-04 22:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='context',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
